# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["-layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "simulator",
    srcs = ["simulator.cpp"],
    copts = [
        "-I/usr/include/libftdi1",
        "-I/usr/include/libusb-1.0",
    ],
    linkopts = [
        "-lftdi1",
        "-lusb-1.0",
    ],
    linkstatic = True,
    deps = [
        "@coralnpu_hw//hw_sim:coralnpu_simulator_headers",
        "@coralnpu_hw//sw/utils/nexus_loader:spi_master",
    ],
    alwayslink = True,
)

cc_binary(
    name = "libcoralnpu_simulator_fpga.so",
    linkshared = True,
    deps = [":simulator"],
)
